# https://blog.catatsuy.org/a/243
# 基本設定
set -g history-limit 50000
set -g display-time 4000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -s escape-time 50
set -g status-interval 10

# Prefix
set-option -g prefix C-q

# マウスでpane選択
set-option -g mouse on

# ダブルクリックでタイルレイアウトに変更
bind -n DoubleClick1Pane select-layout tiled

# KeyBindings(Emacs風pane操作)

unbind 1
bind 1 break-pane
bind 2 split-window -v
bind 3 split-window -h

bind k kill-window
unbind &


# viモードでのキーバインド

# viモードでコピー&ペーストの解説
# 1. Prefix+[ (コピーモード)
# 2. 矢印キーでカーソル移動
# 3. v (選択開始)、V(行選択)、C-v(矩形選択)
# 4. 矢印キーで選択範囲拡張
# 5. y (コピー実行)
# 6. ドキュメントでCmd+V

## vi風コピー&ペースト
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'pbcopy'

# iterm2, tmuxでクリップボードを共有する
# 1. iTerm2の設定：iTerm2 > Preferences > General > Selection > "Applications in terminal may access clipboard"にチェック
# 2. OSC 52サポートを有効にする
# 通常の選択をしたい場合は、optionを押しながら選択する
set -g set-clipboard on
set -g focus-events on