;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	View-scroll-line-backward
	org-cycle-agenda-files
	org-delete-char
	org-kill-line
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	View-scroll-page-backward
	electric-newline-and-maybe-indent
	eval-last-sexp
	mark-whole-buffer
	seq-end
	seq-home
	))
